;guile 3.0.9
;Exercise 3.21
(define (front-ptr queue) (car queue))
(define (rear-ptr queue) (cdr queue))
(define (set-front-ptr! queue item)
	(set-car! queue item))
(define (set-rear-ptr! queue item)
	(set-cdr! queue item))
(define (empty-queue? queue)
	(null? (front-ptr queue)))
(define (make-queue) (cons '() '()))
(define (front-queue queue)
	(if (empty-queue? queue)
			(error "FRONT called with an empty queue" queue)
			(car (front-ptr queue))))
(define (insert-queue! queue item)
	(let ((new-pair (cons item '())))
		(cond ((empty-queue? queue)
					 (set-front-ptr! queue new-pair)
					 (set-rear-ptr! queue new-pair)
					 queue)
					(else
					 (set-cdr! (rear-ptr queue) new-pair)
					 (set-rear-ptr! queue new-pair)
					 queue))))
(define (delete-queue! queue)
	(cond ((empty-queue? queue)
				 (error "DELETE! called with an empty queue" queue))
				(else (set-front-ptr! queue (cdr (front-ptr queue)))
							queue)))


; The list is a pair composed of the front and rear of the list,
; so if you want to print it, just print the front, since all
; items through the end are connected.
(define q1 (make-queue))
(insert-queue! q1 'a)
(format #t "q1 = ~a\n" q1)
(format #t "list q1 = ~a\n" (front-ptr q1))
(insert-queue! q1 'b)
(format #t "q1 = ~a\n" q1)
(format #t "list q1 = ~a\n" (front-ptr q1))
(insert-queue! q1 'c)
(format #t "q1 = ~a\n" q1)
(format #t "list q1 = ~a\n" (front-ptr q1))
(delete-queue! q1)
(format #t "q1 = ~a\n" q1)
(format #t "list q1 = ~a\n" (front-ptr q1))
(delete-queue! q1)
(format #t "q1 = ~a\n" q1)
(format #t "list q1 = ~a\n" (front-ptr q1))
