(include "../journal/stream-v3.scm")
(include "../journal/add-streams.scm")
(define (pi-summands n)
    (cons-stream (/ 1.0 n)
                 (stream-map - (pi-summands (+ n 2)))))
(define pi-stream
    (scale-stream (partial-sums (pi-summands 1)) 4))

(display (stream-ref pi-stream 0))
(newline)
(display (stream-ref pi-stream 1))
(newline)
(display (stream-ref pi-stream 2))
(newline)
(display (stream-ref pi-stream 3))
(newline)
(display (stream-ref pi-stream 4))
(newline)
(display (stream-ref pi-stream 5))
(newline)
(display (stream-ref pi-stream 6))
(newline)
(display (stream-ref pi-stream 7))
(newline)
(newline)

(define (square x) (* x x))

(define (euler-transform s)
    (let ((s0 (stream-ref s 0)) ; Sn 1
          (s1 (stream-ref s 1)) ; Sn
          (s2 (stream-ref s 2))) ; Sn+1
         (cons-stream (- s2 (/ (square (- s2 s1)) (+ s0 (* -2 s1) s2)))
                      (euler-transform (stream-cdr s)))))

(display (stream-ref (euler-transform pi-stream) 0))
(newline)
(display (stream-ref (euler-transform pi-stream) 1))
(newline)
(display (stream-ref (euler-transform pi-stream) 2))
(newline)
(display (stream-ref (euler-transform pi-stream) 3))
(newline)
(display (stream-ref (euler-transform pi-stream) 4))
(newline)
(display (stream-ref (euler-transform pi-stream) 5))
(newline)
(display (stream-ref (euler-transform pi-stream) 6))
(newline)
(display (stream-ref (euler-transform pi-stream) 7))
(newline)
(newline)

(define (make-tableau transform s)
    (cons-stream s (make-tableau transform (transform s))))

(define (accelerated-sequence transform s)
    (stream-map stream-car (make-tableau transform s)))

(display (stream-ref (accelerated-sequence euler-transform pi-stream) 0))
(newline)
(display (stream-ref (accelerated-sequence euler-transform pi-stream) 1))
(newline)
(display (stream-ref (accelerated-sequence euler-transform pi-stream) 2))
(newline)
(display (stream-ref (accelerated-sequence euler-transform pi-stream) 3))
(newline)
(display (stream-ref (accelerated-sequence euler-transform pi-stream) 4))
(newline)
(display (stream-ref (accelerated-sequence euler-transform pi-stream) 5))
(newline)
(display (stream-ref (accelerated-sequence euler-transform pi-stream) 6))
(newline)
(display (stream-ref (accelerated-sequence euler-transform pi-stream) 7))
